services:
  mongodb:
    container_name: sol-wallets-tracker-mongo
    image: mongo:8.0.4
    ports:
      - 27017:27017
    restart: always
    volumes:
      - ./docker-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME:  ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
