name: deploy
on:
  push:
    branches: [ "master" ]
jobs:
  deploy-master:
    runs-on: hoangtv-asus
    steps:
      - uses: actions/checkout@v2
      - name: Copy Code
        run: rm -rf .git && cp -r ./ ~/deploy/sol-wallets-tracker
      - name: Deploy
        run: cd ~/deploy/sol-wallets-tracker && docker compose up -d --build
